<a href="https://colab.research.google.com/github/RutujaBidkar/Pandas_Workplace/blob/main/PandasDay6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
sales = pd.Series([15000,18000,22000,28000,300000])
sales
print(sales)

0     15000
1     18000
2     22000
3     28000
4    300000
dtype: int64

In [10]:
print(sales.sum())
print(sales.mean())
print(sales.max())
print(sales.min())
print(sales.count())

383000
76600.0
300000
15000
5

In [12]:
print(sales[sales>20000])

2     22000
3     28000
4    300000
dtype: int64

In [14]:
print(sales[(sales >15000) & (sales <25000 )])

1    18000
2    22000
dtype: int64

In [17]:
sales = pd.Series([12000, 18000, 15000, 22000, 18000, 25000])
print(sales[sales.isin([12000, 22000, 25000])])

0    12000
3    22000
5    25000
dtype: int64

In [21]:
import pandas as pd

department = pd.Series([
    "IT", "HR", "IT", "Sales",
    "HR", "IT", "Finance", "Sales"
])
print(department.value_counts())

IT         3
HR         2
Sales      2
Finance    1
Name: count, dtype: int64

In [22]:
print(department.nunique())

4

In [23]:
salary = pd.Series([25000, 35000, None, 45000, None, 60000])
salary.isna()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [25]:
salary.isna().sum()
salary[salary.notna()]

0    25000.0
1    35000.0
3    45000.0
5    60000.0
dtype: float64

In [26]:
salary = pd.Series([25000, 35000, None, 45000, None, 60000])
salary.fillna(40000)

0    25000.0
1    35000.0
2     4000.0
3    45000.0
4     4000.0
5    60000.0
dtype: float64

In [27]:
salary.fillna(salary.mean())

0    25000.0
1    35000.0
2    41250.0
3    45000.0
4    41250.0
5    60000.0
dtype: float64

In [29]:
salary = pd.Series([25000, 35000, None, 45000, None, 60000])
salary.dropna().reset_index(drop=True)

0    25000.0
1    35000.0
2    45000.0
3    60000.0
dtype: float64

In [30]:
salary = pd.Series([45000, 30000, 60000, 35000, 50000])
salary.sort_values()

1    30000
3    35000
0    45000
4    50000
2    60000
dtype: int64

In [31]:
salary.sort_values(ascending=False)

2    60000
4    50000
0    45000
3    35000
1    30000
dtype: int64

In [32]:
salary.sort_values(ascending=False).head(2)

2    60000
4    50000
dtype: int64